"""Argument parser construction for the ARC Lucifer CLI."""

from __future__ import annotations

import argparse


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog='lucifer', description='ARC Lucifer clean-room runtime CLI')
    parser.add_argument('--workspace', default='.', help='Workspace root for file and shell actions.')
    parser.add_argument('--db', default=None, help='Optional SQLite event log path.')
    parser.add_argument('--config', default=None, help='Optional JSON config path. Defaults to .arc_lucifer/config.json or ARC_LUCIFER_CONFIG.')
    sub = parser.add_subparsers(dest='command', required=True)

    read_p = sub.add_parser('read', help='Read a file inside the workspace.')
    read_p.add_argument('path')

    write_p = sub.add_parser('write', help='Write a file inside the workspace.')
    write_p.add_argument('path')
    write_p.add_argument('content')
    write_p.add_argument('--confirm', action='store_true', help='Confirm gated actions immediately.')

    delete_p = sub.add_parser('delete', help='Delete a file inside the workspace.')
    delete_p.add_argument('path')
    delete_p.add_argument('--confirm', action='store_true', help='Approve destructive action immediately.')

    shell_p = sub.add_parser('shell', help='Run an allowlisted shell command.')
    shell_p.add_argument('command_text', nargs=argparse.REMAINDER)

    prompt_p = sub.add_parser('prompt', help='Use the managed local model when configured, otherwise route through the deterministic runtime.')
    prompt_p.add_argument('text')
    prompt_p.add_argument('--confirm', action='store_true')
    prompt_p.add_argument('--stream', action='store_true', help='Print streamed text chunks live.')
    prompt_p.add_argument('--json-output', action='store_true', help='Print only the final JSON payload for model prompts.')
    prompt_p.add_argument('--system', default=None, help='Optional system prompt for model execution.')
    prompt_p.add_argument('--binary-path', default=None, help='Path to llamafile binary. Can also come from ARC_LUCIFER_LLAMAFILE_BINARY.')
    prompt_p.add_argument('--model-path', default=None, help='Path to GGUF model file. Can also come from ARC_LUCIFER_LLAMAFILE_MODEL.')
    prompt_p.add_argument('--model-name', default=None, help='Optional model name passed to the backend.')
    prompt_p.add_argument('--host', default=None, help='Override host. Defaults to 127.0.0.1 or ARC_LUCIFER_LLAMAFILE_HOST.')
    prompt_p.add_argument('--port', type=int, default=None, help='Override port or use ARC_LUCIFER_LLAMAFILE_PORT.')
    prompt_p.add_argument('--startup-timeout', type=float, default=None)
    prompt_p.add_argument('--idle-timeout', type=float, default=None)
    prompt_p.add_argument('--temperature', type=float, default=None)
    prompt_p.add_argument('--max-tokens', type=int, default=None)
    prompt_p.add_argument('--keep-alive', action='store_true', help='Keep the managed llamafile process alive between prompt calls.')

    approve_p = sub.add_parser('approve', help='Approve a pending proposal by ID.')
    approve_p.add_argument('proposal_id')

    reject_p = sub.add_parser('reject', help='Reject a pending proposal by ID.')
    reject_p.add_argument('proposal_id')
    reject_p.add_argument('--reason', default='Operator rejected pending proposal.')

    rollback_p = sub.add_parser('rollback', help='Rollback a previously completed proposal by receipt/undo data.')
    rollback_p.add_argument('proposal_id')

    code_p = sub.add_parser('code', help='Line-anchored and symbol-aware code editing commands.')
    code_sub = code_p.add_subparsers(dest='code_command', required=True)
    code_index = code_sub.add_parser('index', help='Index exact lines and symbols for a code file.')
    code_index.add_argument('path')
    code_verify = code_sub.add_parser('verify', help='Verify a code file and parser state.')
    code_verify.add_argument('path')
    code_plan = code_sub.add_parser('plan', help='Create a line/symbol-grounded edit plan.')
    code_plan.add_argument('path')
    code_plan.add_argument('instruction')
    code_plan.add_argument('--symbol', default=None)
    code_replace_range = code_sub.add_parser('replace-range', help='Replace an exact line range.')
    code_replace_range.add_argument('path')
    code_replace_range.add_argument('start_line', type=int)
    code_replace_range.add_argument('end_line', type=int)
    code_replace_range.add_argument('replacement_text')
    code_replace_range.add_argument('--expected-hash', default=None)
    code_replace_range.add_argument('--confirm', action='store_true')
    code_replace_range.add_argument('--reason', default='')
    code_replace_symbol = code_sub.add_parser('replace-symbol', help='Replace an exact Python symbol block.')
    code_replace_symbol.add_argument('path')
    code_replace_symbol.add_argument('symbol_name')
    code_replace_symbol.add_argument('replacement_text')
    code_replace_symbol.add_argument('--expected-hash', default=None)
    code_replace_symbol.add_argument('--confirm', action='store_true')
    code_replace_symbol.add_argument('--reason', default='')

    trace_p = sub.add_parser('trace', help='Render the current event trace to HTML.')
    trace_p.add_argument('--output', default='trace.html')

    export_p = sub.add_parser('export', help='Export event history or back up the SQLite database.')
    export_p.add_argument('--jsonl', default=None, help='Write all events as JSONL to this path.')
    export_p.add_argument('--sqlite-backup', default=None, help='Copy the SQLite database to this path.')

    import_p = sub.add_parser('import', help='Import previously exported JSONL events into the current workspace DB.')
    import_p.add_argument('--jsonl', required=True, help='JSONL file created by export --jsonl.')

    sub.add_parser('compact', help='Checkpoint WAL and vacuum the SQLite event database.')
    sub.add_parser('info', help='Show runtime paths and database statistics.')

    monitor_p = sub.add_parser('monitor', help='Show a live operator monitor panel from persisted state.')
    sub.add_parser('failures', help='Show recorded fallback/degraded execution events.')
    monitor_p.add_argument('--watch', type=float, default=0.0, help='Refresh interval in seconds. 0 prints once.')
    monitor_p.add_argument('--iterations', type=int, default=1, help='How many refreshes to print when --watch is set.')

    doctor_p = sub.add_parser('doctor', help='Run production diagnostics for workspace, DB, local model config, and release gates.')
    doctor_p.add_argument('--json-output', action='store_true', help='Emit only the final JSON diagnostic payload.')
    doctor_p.add_argument('--release-gate', action='store_true', help='Include repo release-hygiene checks when running inside the project tree.')
    doctor_p.add_argument('--strict', action='store_true', help='Treat warnings as errors for operator/release gating.')

    config_p = sub.add_parser('config', help='Inspect or write the runtime JSON config file.')
    config_sub = config_p.add_subparsers(dest='config_command', required=True)
    config_show = config_sub.add_parser('show', help='Print the resolved config.')
    config_show.add_argument('--resolved', action='store_true', help='Include effective defaults.')
    config_init = config_sub.add_parser('init', help='Write a starter config file.')
    config_init.add_argument('--force', action='store_true', help='Overwrite existing config file.')

    model_p = sub.add_parser('model', help='Manage open-ended model backends and GGUF profiles.')
    model_sub = model_p.add_subparsers(dest='model_command', required=True)
    model_sub.add_parser('backends', help='List registered runtime backends.')
    model_sub.add_parser('profiles', help='List stored model profiles.')
    model_show = model_sub.add_parser('show-profile', help='Show a stored model profile.')
    model_show.add_argument('name')
    model_register = model_sub.add_parser('register-profile', help='Register a model profile for any local or external backend.')
    model_register.add_argument('name')
    model_register.add_argument('--backend-type', required=True, help='Examples: llamafile, gguf_local, openai_compatible, custom')
    model_register.add_argument('--binary-path', default=None)
    model_register.add_argument('--model-path', default=None)
    model_register.add_argument('--endpoint', default=None)
    model_register.add_argument('--notes', default='')
    model_register.add_argument('--intended-use', default='')
    model_register.add_argument('--training-ready', action='store_true')
    model_register.add_argument('--activate', action='store_true')
    model_register.add_argument('--param', action='append', default=[], help='Extra key=value metadata')
    model_activate = model_sub.add_parser('activate-profile', help='Set the active model profile.')
    model_activate.add_argument('name')
    model_compare = model_sub.add_parser('compare-profiles', help='Compare one or more stored profiles.')
    model_compare.add_argument('names', nargs='+')

    train_p = sub.add_parser('train', help='Export training corpora for future custom GGUF/model work.')
    train_sub = train_p.add_subparsers(dest='train_command', required=True)
    train_supervised = train_sub.add_parser('export-supervised', help='Export supervised training JSONL from persisted state.')
    train_supervised.add_argument('--output', required=True)
    train_pref = train_sub.add_parser('export-preferences', help='Export preference-pair JSONL from candidate scoring state.')
    train_pref.add_argument('--output', required=True)

    sub.add_parser('state', help='Print projected state as JSON.')
    sub.add_parser('commands', help='List the command surface.')
    sub.add_parser('bench', help='Run the built-in smoke benchmark suite.')
    self_p = sub.add_parser('self-improve', help='Analyze, plan, and scaffold improvement runs from persisted state.')
    self_sub = self_p.add_subparsers(dest='self_command', required=True)
    self_sub.add_parser('analyze', help='Summarize the next prioritized engineering targets from current state.')
    self_plan = self_sub.add_parser('plan', help='Turn current improvement targets into a concrete repo plan.')
    self_plan.add_argument('--target-key', default=None, help='Optional target key from self-improve analyze.')
    self_scaffold = self_sub.add_parser('scaffold', help='Create a self-improvement sandbox/worktree from the current plan.')
    self_scaffold.add_argument('--target-key', default=None, help='Optional target key from self-improve analyze.')
    self_validate = self_sub.add_parser('validate-run', help='Run manifest validation commands inside a self-improvement worktree.')
    self_validate.add_argument('run_id')
    self_validate.add_argument('--timeout', type=int, default=120)
    self_promote = self_sub.add_parser('promote', help='Promote a validated self-improvement worktree back into the repo.')
    self_promote.add_argument('run_id')
    self_promote.add_argument('--force', action='store_true')
    self_patch = self_sub.add_parser('apply-patch', help='Apply an exact patch inside a self-improvement worktree.')
    self_patch.add_argument('run_id')
    self_patch.add_argument('--path', required=True)
    self_patch.add_argument('--replacement', required=True)
    self_patch.add_argument('--symbol', default=None)
    self_patch.add_argument('--start-line', type=int, default=None)
    self_patch.add_argument('--end-line', type=int, default=None)
    self_patch.add_argument('--expected-hash', default=None)
    self_patch.add_argument('--reason', default='')
    self_patch.add_argument('--validate', action='store_true')
    self_candidates = self_sub.add_parser('generate-candidates', help='Create deterministic candidate patches for a self-improvement run.')
    self_candidates.add_argument('run_id')
    self_candidates.add_argument('--path', required=True)
    self_candidates.add_argument('--replacement', required=True)
    self_candidates.add_argument('--symbol', default=None)
    self_candidates.add_argument('--start-line', type=int, default=None)
    self_candidates.add_argument('--end-line', type=int, default=None)
    self_candidates.add_argument('--expected-hash', default=None)
    self_candidates.add_argument('--reason', default='')
    self_score = self_sub.add_parser('score-candidates', help='Validate and score generated candidate patches.')
    self_score.add_argument('run_id')
    self_score.add_argument('--timeout', type=int, default=120)
    self_best = self_sub.add_parser('best-candidate', help='Show the best currently scored candidate.')
    self_best.add_argument('run_id')
    self_exec_best = self_sub.add_parser('execute-best', help='Execute the best scored candidate in the main run worktree.')
    self_exec_best.add_argument('run_id')
    self_exec_best.add_argument('--timeout', type=int, default=120)
    self_exec_best.add_argument('--promote', action='store_true')
    self_exec_best.add_argument('--force-promote', action='store_true')
    self_exec_best.add_argument('--no-quarantine', action='store_true')
    self_fault = self_sub.add_parser('inject-fault', help='Inject a deterministic failure into a self-improvement run worktree.')
    self_fault.add_argument('run_id')
    self_fault.add_argument('--kind', required=True, choices=['delete_target_file', 'python_syntax_break', 'force_validation_failure', 'corrupt_candidate_tree'])
    self_fault.add_argument('--path', default=None)
    self_fault.add_argument('--note', default='')
    self_adv = self_sub.add_parser('adversarial-cycle', help='Inject a fault and execute a validation cycle under stress.')
    self_adv.add_argument('run_id')
    self_adv.add_argument('--kind', required=True, choices=['delete_target_file', 'python_syntax_break', 'force_validation_failure', 'corrupt_candidate_tree'])
    self_adv.add_argument('--path', required=True)
    self_adv.add_argument('--replacement', required=True)
    self_adv.add_argument('--symbol', default=None)
    self_adv.add_argument('--start-line', type=int, default=None)
    self_adv.add_argument('--end-line', type=int, default=None)
    self_adv.add_argument('--expected-hash', default=None)
    self_adv.add_argument('--reason', default='')
    self_adv.add_argument('--timeout', type=int, default=120)
    self_cycle = self_sub.add_parser('execute-cycle', help='Patch, validate, and optionally promote a self-improvement run.')
    self_cycle.add_argument('run_id')
    self_cycle.add_argument('--path', required=True)
    self_cycle.add_argument('--replacement', required=True)
    self_cycle.add_argument('--symbol', default=None)
    self_cycle.add_argument('--start-line', type=int, default=None)
    self_cycle.add_argument('--end-line', type=int, default=None)
    self_cycle.add_argument('--expected-hash', default=None)
    self_cycle.add_argument('--reason', default='')
    self_cycle.add_argument('--timeout', type=int, default=120)
    self_cycle.add_argument('--no-validate', action='store_true')
    self_cycle.add_argument('--promote', action='store_true')
    self_cycle.add_argument('--force-promote', action='store_true')
    self_cycle.add_argument('--no-quarantine', action='store_true')
    self_review = self_sub.add_parser('review-run', help='Review the promotion evidence bundle for a self-improvement run.')
    self_review.add_argument('run_id')

    fixnet_p = sub.add_parser('fixnet', help='FixNet repair intelligence: storage, consensus, novelty, and embedded archive mirrors.')
    fixnet_sub = fixnet_p.add_subparsers(dest='fixnet_command', required=True)
    fixnet_register = fixnet_sub.add_parser('register', help='Register a fix with semantic lineage and novelty scoring.')
    fixnet_register.add_argument('--title', required=True)
    fixnet_register.add_argument('--error-type', required=True)
    fixnet_register.add_argument('--error-signature', required=True)
    fixnet_register.add_argument('--solution', required=True)
    fixnet_register.add_argument('--summary', default='')
    fixnet_register.add_argument('--keywords', default='')
    fixnet_register.add_argument('--context-json', default='{}')
    fixnet_register.add_argument('--evidence-json', default='{}')
    fixnet_register.add_argument('--linked-event-id', action='append', default=[])
    fixnet_register.add_argument('--linked-run-id', action='append', default=[])
    fixnet_register.add_argument('--linked-proposal-id', action='append', default=[])
    fixnet_register.add_argument('--auto-embed', action='store_true')
    fixnet_register.add_argument('--archive-branch-id', default='archive_branch_main')
    fixnet_embed = fixnet_sub.add_parser('embed', help='Embed an existing fix into the archive-visible mirror.')
    fixnet_embed.add_argument('fix_id')
    fixnet_embed.add_argument('--archive-branch-id', default='archive_branch_main')
    fixnet_sub.add_parser('stats', help='Show FixNet statistics and consensus tier counts.')
    fixnet_sync = fixnet_sub.add_parser('sync-archive', help='Update live-linked embedded archive metadata for an existing fix.')
    fixnet_sync.add_argument('fix_id')
    fixnet_sync.add_argument('--status', default='live')
    fixnet_sync.add_argument('--retirement-at', default=None)

    trust_p = sub.add_parser('trust', help='Record or inspect tool/model trust profiles.')
    trust_sub = trust_p.add_subparsers(dest='trust_command', required=True)
    trust_record = trust_sub.add_parser('record', help='Record a tool or subsystem outcome.')
    trust_record.add_argument('tool_name')
    trust_record.add_argument('--status', choices=['success', 'failure'], required=True)
    trust_record.add_argument('--notes', default='')
    trust_record.add_argument('--evidence-json', default='{}')
    trust_sub.add_parser('stats', help='Show trust profile statistics.')

    curriculum_p = sub.add_parser('curriculum', help='Record or inspect long-horizon curriculum memory.')
    curriculum_sub = curriculum_p.add_subparsers(dest='curriculum_command', required=True)
    curriculum_record = curriculum_sub.add_parser('record', help='Record a curriculum theme, skill, or failure cluster.')
    curriculum_record.add_argument('--theme', required=True)
    curriculum_record.add_argument('--skill', default=None)
    curriculum_record.add_argument('--failure-cluster', default=None)
    curriculum_record.add_argument('--outcome', default='observed')
    curriculum_record.add_argument('--notes', default='')
    curriculum_sub.add_parser('stats', help='Show curriculum memory statistics.')

    directive_p = sub.add_parser('directive', help='Persist long-lived operator directives for the runtime.')
    directive_sub = directive_p.add_subparsers(dest='directive_command', required=True)
    directive_add = directive_sub.add_parser('add', help='Add an active directive to the directive ledger.')
    directive_add.add_argument('--title', required=True)
    directive_add.add_argument('--instruction', required=True)
    directive_add.add_argument('--priority', type=int, default=50)
    directive_add.add_argument('--scope', default='global')
    directive_add.add_argument('--constraints', default='')
    directive_add.add_argument('--success-conditions', default='')
    directive_add.add_argument('--abort-conditions', default='')
    directive_add.add_argument('--persistence-mode', default='forever')
    directive_add.add_argument('--issuer', default='operator')
    directive_add.add_argument('--supersedes', default=None)
    directive_complete = directive_sub.add_parser('complete', help='Mark a directive complete or superseded.')
    directive_complete.add_argument('directive_id')
    directive_complete.add_argument('--status', default='complete')
    directive_sub.add_parser('stats', help='Show directive ledger status.')

    continuity_p = sub.add_parser('continuity', help='Boot, heartbeat, and inspect runtime continuity state.')
    continuity_sub = continuity_p.add_subparsers(dest='continuity_command', required=True)
    continuity_boot = continuity_sub.add_parser('boot', help='Record a continuity boot receipt and choose primary/fallback mode.')
    continuity_boot.add_argument('--fallback-available', action='store_true')
    continuity_boot.add_argument('--notes', default='')
    continuity_heartbeat = continuity_sub.add_parser('heartbeat', help='Update continuity heartbeat state.')
    continuity_heartbeat.add_argument('--mode', default=None)
    continuity_heartbeat.add_argument('--notes', default='')
    continuity_sub.add_parser('status', help='Show continuity identity, boot receipts, and watchdog health.')

    goal_p = sub.add_parser('goal', help='Compile operator intent into a structured goal contract.')
    goal_p.add_argument('text')
    goal_p.add_argument('--priority', type=int, default=50)

    shadow_p = sub.add_parser('shadow', help='Run a shadow predicted-vs-actual comparison for a command.')
    shadow_p.add_argument('text')
    shadow_p.add_argument('--predicted-status', default='approve')
    shadow_p.add_argument('--confirm', action='store_true')

    memory_p = sub.add_parser('memory', help='Manage live, warm, and archived memory tiers.')
    memory_sub = memory_p.add_subparsers(dest='memory_command', required=True)
    memory_sub.add_parser('status', help='Show archive manifests and memory update history.')
    memory_archive = memory_sub.add_parser('archive-now', help='Mirror a memory item into the archive branch early while keeping it live until its scheduled retirement date.')
    memory_archive.add_argument('event_id')
    memory_archive.add_argument('--reason', default='manual_override')
    memory_archive.add_argument('--archive-branch-id', default='archive_branch_main')
    memory_sync = memory_sub.add_parser('sync', help='Sync mirrored live memory into the archive branch.')
    memory_sync.add_argument('--event-id', default=None)
    memory_search = memory_sub.add_parser('search', help='Search readable live/archive memory using title, summary, and keyword ranking.')
    memory_search.add_argument('query')
    memory_search.add_argument('--limit', type=int, default=10)


    robot_p = sub.add_parser('robot', help='Optional bounded robotics bridge commands.')
    robot_sub = robot_p.add_subparsers(dest='robot_command', required=True)
    robot_sub.add_parser('describe', help='Describe optional robot adapters and doctrine.')
    robot_sub.add_parser('state-template', help='Print a canonical robot state template.')
    robot_safety = robot_sub.add_parser('safety-check', help='Run deterministic interlock checks for a bounded robot action.')
    robot_safety.add_argument('--state-json', required=True)
    robot_safety.add_argument('--action', required=True)
    robot_safety.add_argument('--subsystem', default='dog_body')
    robot_safety.add_argument('--params-json', default='{}')
    robot_perform = robot_sub.add_parser('perform', help='Execute a bounded mock robot action when interlocks allow it.')
    robot_perform.add_argument('--state-json', required=True)
    robot_perform.add_argument('--action', required=True)
    robot_perform.add_argument('--subsystem', default='dog_body')
    robot_perform.add_argument('--params-json', default='{}')

    mapping_p = sub.add_parser('mapping', help='Optional local mapping and navigation commands.')
    mapping_sub = mapping_p.add_subparsers(dest='mapping_command', required=True)
    mapping_sub.add_parser('describe', help='Describe the local mapping layer.')
    mapping_sub.add_parser('state-template', help='Print a canonical mapping state template.')
    mapping_cov = mapping_sub.add_parser('coverage', help='Summarize occupancy-grid coverage.')
    mapping_cov.add_argument('--state-json', required=True)
    mapping_ingest = mapping_sub.add_parser('ingest-update', help='Apply grid updates to a mapping state.')
    mapping_ingest.add_argument('--state-json', required=True)
    mapping_ingest.add_argument('--updates-json', required=True)
    mapping_ingest.add_argument('--robot-position-json', default=None)
    mapping_route = mapping_sub.add_parser('plan-route', help='Plan a grid route over the current mapping state.')
    mapping_route.add_argument('--state-json', required=True)
    mapping_route.add_argument('--goal-json', required=True)

    spatial_p = sub.add_parser('spatial', help='Canonical spatial truth layer commands.')
    spatial_sub = spatial_p.add_subparsers(dest='spatial_command', required=True)
    spatial_sub.add_parser('describe', help='Describe the spatial truth layer.')
    spatial_sub.add_parser('state-template', help='Print an empty spatial truth state.')
    spatial_ingest = spatial_sub.add_parser('ingest-observation', help='Add one structured observation into spatial truth.')
    spatial_ingest.add_argument('--state-json', required=True)
    spatial_ingest.add_argument('--observation-json', required=True)
    spatial_bt = spatial_sub.add_parser('ingest-bt-signal', help='Add one bluetooth signal observation into spatial truth.')
    spatial_bt.add_argument('--state-json', required=True)
    spatial_bt.add_argument('--signal-json', required=True)
    spatial_anchor = spatial_sub.add_parser('upsert-anchor', help='Insert or update one spatial anchor.')
    spatial_anchor.add_argument('--state-json', required=True)
    spatial_anchor.add_argument('--anchor-json', required=True)
    spatial_summary = spatial_sub.add_parser('summarize', help='Summarize confidence and semantic labels in spatial truth.')
    spatial_summary.add_argument('--state-json', required=True)



    bt_p = sub.add_parser('bt', help='Optional trusted bluetooth bridge commands.')
    bt_sub = bt_p.add_subparsers(dest='bt_command', required=True)
    bt_sub.add_parser('describe', help='Describe bluetooth bridge doctrine, profiles, and signal modes.')
    bt_sub.add_parser('device-template', help='Print a canonical trusted-device template.')
    bt_list = bt_sub.add_parser('trusted-list', help='List trusted bluetooth devices.')
    bt_list.add_argument('--devices-json', required=True)
    bt_register = bt_sub.add_parser('register-device', help='Register or update a trusted bluetooth device.')
    bt_register.add_argument('--devices-json', required=True)
    bt_register.add_argument('--device-json', required=True)
    bt_inspect = bt_sub.add_parser('inspect-device', help='Show a trusted bluetooth device record by device ID.')
    bt_inspect.add_argument('--devices-json', required=True)
    bt_inspect.add_argument('--device-id', required=True)
    bt_signal = bt_sub.add_parser('signal-summary', help='Summarize visible bluetooth device signals.')
    bt_signal.add_argument('--devices-json', required=True)
    bt_signal_obs = bt_sub.add_parser('signal-observation', help='Project one trusted bluetooth device into a spatial signal payload.')
    bt_signal_obs.add_argument('--devices-json', required=True)
    bt_signal_obs.add_argument('--device-id', required=True)
    bt_policy = bt_sub.add_parser('policy-check', help='Run bounded bluetooth profile policy checks.')
    bt_policy.add_argument('--devices-json', required=True)
    bt_policy.add_argument('--action', required=True)
    bt_policy.add_argument('--device-id', default=None)
    bt_policy.add_argument('--profile', default=None)
    bt_policy.add_argument('--params-json', default='{}')
    bt_policy.add_argument('--operator-approved', action='store_true')
    bt_perform = bt_sub.add_parser('perform', help='Perform a bounded bluetooth action or local signal operation.')
    bt_perform.add_argument('--devices-json', required=True)
    bt_perform.add_argument('--action', required=True)
    bt_perform.add_argument('--device-id', default=None)
    bt_perform.add_argument('--profile', default=None)
    bt_perform.add_argument('--params-json', default='{}')
    bt_perform.add_argument('--operator-approved', action='store_true')

    geo_p = sub.add_parser('geo', help='Optional geo overlay and anchor-vault commands.')
    geo_sub = geo_p.add_subparsers(dest='geo_command', required=True)
    geo_sub.add_parser('describe', help='Describe the geo overlay layer.')
    geo_sub.add_parser('anchor-template', help='Print a canonical geo anchor template.')
    geo_register = geo_sub.add_parser('register-anchor', help='Register an anchor into the local geo vault.')
    geo_register.add_argument('--anchors-json', required=True)
    geo_register.add_argument('--anchor-json', required=True)
    geo_nearest = geo_sub.add_parser('nearest-anchor', help='Find the nearest registered anchor.')
    geo_nearest.add_argument('--anchors-json', required=True)
    geo_nearest.add_argument('--lat', type=float, required=True)
    geo_nearest.add_argument('--lon', type=float, required=True)
    geo_tile = geo_sub.add_parser('tile-summary', help='Summarize anchors into tile buckets.')
    geo_tile.add_argument('--anchors-json', required=True)
    geo_tile.add_argument('--zoom', type=int, default=16)

    return parser
