#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
ENV_FILE="$ROOT/.env.direct-runtime"
[[ -f "$ENV_FILE" ]] || cp "$ROOT/.env.direct-runtime.example" "$ENV_FILE"
usage(){ echo "Usage: $0 --gguf /abs/path/model.gguf --binary /abs/path/llama-cli | --llamafile /abs/path/model.llamafile" >&2; exit 2; }
GGUF=""; BINARY=""; LLAMAFILE=""
while [[ $# -gt 0 ]]; do case "$1" in --gguf) GGUF="$2"; shift 2 ;; --binary) BINARY="$2"; shift 2 ;; --llamafile) LLAMAFILE="$2"; shift 2 ;; -h|--help) usage ;; *) usage ;; esac; done
if [[ -n "$LLAMAFILE" ]]; then [[ -f "$LLAMAFILE" ]] || { echo "Missing llamafile: $LLAMAFILE" >&2; exit 2; }; COMMAND_TEMPLATE="$LLAMAFILE -f {combined_prompt_file}"; MODEL_PATH=""; else [[ -n "$GGUF" && -n "$BINARY" ]] || { echo "--gguf and --binary must be provided together" >&2; exit 2; }; [[ -f "$GGUF" ]] || { echo "Missing GGUF: $GGUF" >&2; exit 2; }; COMMAND_TEMPLATE="$BINARY -m {model} -f {combined_prompt_file}"; MODEL_PATH="$GGUF"; fi
python3 - "$ENV_FILE" "$MODEL_PATH" "$COMMAND_TEMPLATE" <<'PY'
from pathlib import Path
import sys

def q(v: str) -> str:
    if not v: return v
    return repr(v) if (any(ch.isspace() for ch in v) or any(ch in v for ch in "'\"")) else v
p=Path(sys.argv[1]); model=sys.argv[2]; command=sys.argv[3]
existing={}
if p.exists():
    for raw in p.read_text(encoding='utf-8').splitlines():
        line=raw.strip()
        if not line or line.startswith('#') or '=' not in line: continue
        k,v=line.split('=',1); existing[k.strip()]=v.strip().strip('"').strip("'")
order=['COGNITION_RUNTIME_ADAPTER','COGNITION_MODEL_PATH','COGNITION_COMMAND_TEMPLATE','COGNITION_TIMEOUT_SECONDS','COGNITION_FIRST_OUTPUT_TIMEOUT_SECONDS','COGNITION_IDLE_TIMEOUT_SECONDS','COGNITION_MAX_OUTPUT_BYTES','COGNITION_SYSTEM_PROMPT','COGNITION_EXEMPLAR_ARTIFACT']
existing['COGNITION_RUNTIME_ADAPTER']='command'; existing['COGNITION_MODEL_PATH']=model; existing['COGNITION_COMMAND_TEMPLATE']=command
existing.setdefault('COGNITION_TIMEOUT_SECONDS','120'); existing.setdefault('COGNITION_FIRST_OUTPUT_TIMEOUT_SECONDS','30'); existing.setdefault('COGNITION_IDLE_TIMEOUT_SECONDS','20'); existing.setdefault('COGNITION_MAX_OUTPUT_BYTES','262144'); existing.setdefault('COGNITION_SYSTEM_PROMPT','Plan, critique, repair, calibrate. Be bounded and honest.'); existing.setdefault('COGNITION_EXEMPLAR_ARTIFACT','exports/candidates/darpa_functional/exemplar_train/artifact_manifest.json')
out=['# Generated by scripts/operator/register_gguf_runtime.sh']
for key in order: out.append(f'{key}={q(existing.get(key,""))}')
for key in sorted(existing):
    if key not in order: out.append(f'{key}={q(existing[key])}')
p.write_text('\n'.join(out)+'\n', encoding='utf-8')
PY
printf 'Updated %s\n' "$ENV_FILE"
