#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
PYTHON_BIN="python3"
ORIG_COGNITION_RUNTIME_ADAPTER="${COGNITION_RUNTIME_ADAPTER-}"
ORIG_COGNITION_MODEL_PATH="${COGNITION_MODEL_PATH-}"
ORIG_COGNITION_COMMAND_TEMPLATE="${COGNITION_COMMAND_TEMPLATE-}"
ORIG_COGNITION_EXEMPLAR_ARTIFACT="${COGNITION_EXEMPLAR_ARTIFACT-}"
ORIG_COGNITION_SYSTEM_PROMPT="${COGNITION_SYSTEM_PROMPT-}"
ORIG_COGNITION_TIMEOUT_SECONDS="${COGNITION_TIMEOUT_SECONDS-}"
ORIG_COGNITION_FIRST_OUTPUT_TIMEOUT_SECONDS="${COGNITION_FIRST_OUTPUT_TIMEOUT_SECONDS-}"
ORIG_COGNITION_IDLE_TIMEOUT_SECONDS="${COGNITION_IDLE_TIMEOUT_SECONDS-}"
ORIG_COGNITION_MAX_OUTPUT_BYTES="${COGNITION_MAX_OUTPUT_BYTES-}"
if [[ -x "$ROOT/.venv/bin/python" ]]; then PYTHON_BIN="$ROOT/.venv/bin/python"; fi
if [[ -f .env.direct-runtime ]]; then set -a; source .env.direct-runtime; set +a; elif [[ -f .env ]]; then set -a; source .env; set +a; fi
[[ -n "$ORIG_COGNITION_RUNTIME_ADAPTER" ]] && COGNITION_RUNTIME_ADAPTER="$ORIG_COGNITION_RUNTIME_ADAPTER"
if [[ -n "$ORIG_COGNITION_RUNTIME_ADAPTER" && -z "$ORIG_COGNITION_COMMAND_TEMPLATE" ]]; then COGNITION_COMMAND_TEMPLATE=""; fi
if [[ -n "$ORIG_COGNITION_RUNTIME_ADAPTER" && -z "$ORIG_COGNITION_MODEL_PATH" ]]; then COGNITION_MODEL_PATH=""; fi
[[ -n "$ORIG_COGNITION_MODEL_PATH" ]] && COGNITION_MODEL_PATH="$ORIG_COGNITION_MODEL_PATH"
[[ -n "$ORIG_COGNITION_COMMAND_TEMPLATE" ]] && COGNITION_COMMAND_TEMPLATE="$ORIG_COGNITION_COMMAND_TEMPLATE"
[[ -n "$ORIG_COGNITION_EXEMPLAR_ARTIFACT" ]] && COGNITION_EXEMPLAR_ARTIFACT="$ORIG_COGNITION_EXEMPLAR_ARTIFACT"
[[ -n "$ORIG_COGNITION_SYSTEM_PROMPT" ]] && COGNITION_SYSTEM_PROMPT="$ORIG_COGNITION_SYSTEM_PROMPT"
[[ -n "$ORIG_COGNITION_TIMEOUT_SECONDS" ]] && COGNITION_TIMEOUT_SECONDS="$ORIG_COGNITION_TIMEOUT_SECONDS"
[[ -n "$ORIG_COGNITION_FIRST_OUTPUT_TIMEOUT_SECONDS" ]] && COGNITION_FIRST_OUTPUT_TIMEOUT_SECONDS="$ORIG_COGNITION_FIRST_OUTPUT_TIMEOUT_SECONDS"
[[ -n "$ORIG_COGNITION_IDLE_TIMEOUT_SECONDS" ]] && COGNITION_IDLE_TIMEOUT_SECONDS="$ORIG_COGNITION_IDLE_TIMEOUT_SECONDS"
[[ -n "$ORIG_COGNITION_MAX_OUTPUT_BYTES" ]] && COGNITION_MAX_OUTPUT_BYTES="$ORIG_COGNITION_MAX_OUTPUT_BYTES"
ADAPTER="${COGNITION_RUNTIME_ADAPTER:-command}"
MODEL_PATH="${COGNITION_MODEL_PATH:-}"
COMMAND_TEMPLATE="${COGNITION_COMMAND_TEMPLATE:-}"
ARTIFACT_PATH="${COGNITION_EXEMPLAR_ARTIFACT:-$ROOT/exports/candidates/darpa_functional/exemplar_train/artifact_manifest.json}"
SYSTEM_PROMPT="${COGNITION_SYSTEM_PROMPT:-Plan, critique, repair, calibrate. Be bounded and honest.}"
TIMEOUT_SECONDS="${COGNITION_TIMEOUT_SECONDS:-120}"
FIRST_OUTPUT_TIMEOUT_SECONDS="${COGNITION_FIRST_OUTPUT_TIMEOUT_SECONDS:-30}"
IDLE_TIMEOUT_SECONDS="${COGNITION_IDLE_TIMEOUT_SECONDS:-20}"
MAX_OUTPUT_BYTES="${COGNITION_MAX_OUTPUT_BYTES:-262144}"
[[ $# -lt 1 ]] && { echo 'Usage: scripts/operator/run_local_prompt.sh "your prompt here"' >&2; exit 2; }
PROMPT="$1"; RECEIPT_DIR="$ROOT/reports/user_runs"; mkdir -p "$RECEIPT_DIR"; STAMP="$(date -u +%Y%m%dT%H%M%SZ)"; RECEIPT_PATH="$RECEIPT_DIR/runtime_receipt_${ADAPTER}_${STAMP}.json"
COMMON_ARGS=(--adapter "$ADAPTER" --prompt "$PROMPT" --system-prompt "$SYSTEM_PROMPT" --receipt-path "$RECEIPT_PATH" --timeout-seconds "$TIMEOUT_SECONDS" --first-output-timeout-seconds "$FIRST_OUTPUT_TIMEOUT_SECONDS" --idle-timeout-seconds "$IDLE_TIMEOUT_SECONDS" --max-output-bytes "$MAX_OUTPUT_BYTES")
if [[ "$ADAPTER" == "exemplar" ]]; then "$PYTHON_BIN" scripts/execution/run_direct_candidate.py "${COMMON_ARGS[@]}" --artifact "$ARTIFACT_PATH"; else [[ -z "$COMMAND_TEMPLATE" ]] && { echo 'COGNITION_COMMAND_TEMPLATE is required when adapter=command' >&2; exit 2; }; MODEL_ARGS=(); [[ -n "$MODEL_PATH" ]] && MODEL_ARGS+=(--model "$MODEL_PATH"); "$PYTHON_BIN" scripts/execution/run_direct_candidate.py "${COMMON_ARGS[@]}" --command-template "$COMMAND_TEMPLATE" "${MODEL_ARGS[@]}"; fi
echo "Receipt written to: $RECEIPT_PATH"
